name: Build execution

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
            runs-on: [macOS-latest, ubuntu-latest, windows-latest]
    name: ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v2
    - name: Build preparation
      run: mkdir build && cd build
    - name: CMake execution
      run: cmake --build cmake_build_dir --target INSTALL
    - name: Make execution
      run: make
    - name: Install distcheck
      run: make install
